README.md

He añadido los logos de los canales deportivos, informativos, musicales, infantiles, autonómicos y unos cuantos de los locales. He añadido los m3u8 de CyL7 y el Canal Parlamento. También añadido canales como La8 CyL, Distrito TV, Televisión Murciana, EITB3, EITB4, La 2 Catalunya, etc; y canales internacionales como Antena3 Internacional, Atreseries Internacional, Atrescine, ¡Hola! TV, Cincomas, TVE Internacional, star TVE, TV3 CAT, franceinfo:, Euronews. Y para acabar he cambiado algunos nombres de algunos canales que estaban mal escritos como RTV Castilla y León -> CyL8 y otros.

Nuevos canales, logos y m3u8

---

TELEVISION.md

He reemplazado los cinco logos que aun quedaban en formato SVG (Bon Dia TV (x2), Canal Reus TV, TVE Internacional, CNN, y Animal Planet Live) por enlaces a PNGs de 320px de anchura

Reemplazados logos SVG por enlaces a PNGs

---

TELEVISION.md

Faltaban espacios antes de algunos separadores de celda en las tablas. También faltaba un guión en la resolución del canal "Cancionero TV" y sobraba un espacio en la resolución de "DW".

Añadidos espacios faltantes en la tabla

---

TELEVISION.md

TPA8, eliminado, sin emisión por internet, es TPA7 una hora mas tarde.
TPA9, eliminado, no existe.
TeleAsturias, eliminado, no emite.
EsAsturias, eliminado, emisión con token.

Update canales Asturias

---

RADIO.md

Radio Zaragoza, perteneciente al grupo de emisoras de La Cadena Ser.

Add Radio Zaragoza

---

TELEVISION.md

Borrar Canal Andalucía Turismo , Flamenco y Cocina dejan de emitir en directo y pasan a la categoría de Vídeos bajo demanda. Así mismo se ve afectado el canal infantil La Banda. :-(

Delete Canales Tematicos Canal Andalucia

---

TELEVISION.md

Borrar la webcam de Fallas Valencia,ya no trasmite y Borrar el link de youtube Malaga 24H Cambia muy a menudo y solo dura 2 dias.

Remove webcam Fallas y youtube link Malaga 24H

---

TELEVISION.md

Cambio de Nombre del canal mi tierra tv...polémico por no tener licencia. Por el nuevo canal con licencia de emisión, Ahora tv. La emisión online utiliza el mismo enlace.
ahora TV es un nuevo canal de televisión local de Tenerife. Contamos con licencia para la prestación del servicio de comunicación audiovisual de televisión digital local en Santa Cruz de Tenerife, Canal 24.

Cambio de Nombre y web de Mi tierra  tv

---

RADIO.md

Corrijo varios logos mal puestos de emisoras Aragonesas de la SER , tienen logo de TPA Asturias :-)
Update completo de Rumba FM Zaragoza

Aragon : Corregir varios logos mal y Update Rumba FM

---

TELEVISION.md

Aunque la emisión web hoy esta caída , te pongo corrección ya que la web no carga con https.
Puntualizar Que el link a la tv en directo seria: http://player.streamingconnect.com/gcm/monitores/directo8.php
no: http://mastvhuelva.com/ . Lo dejo tu criterio.

Update: Más TV Huelva https to http web link

---

RADIO.md

https://www.eldiario.es/canariasahora/tenerifeahora/sociedad/Cierran-repentinamente-Radio-Dia-Television_0_893811714.html

Delete Radio El Día cese de Actividad

---

RADIO.md

Crónicas De Lanzarote: no existe como tal desde su unión con la Cope en el 2013. En la actualidad no tiene ninguna emisión oficial,ni en su web, ni en la COPE.
https://www.cronicasdelanzarote.es/articulo/sociedad/cronicas-radio-cadena-cope/20130109235604175577.html

Update Teide Radio Delete Cronicas De Lanzarote

---

TELEVISION.md

https://www.eldia.es/tenerife/2020/05/12/cabildo-cierra-television-insular-destinar/1077922.html

Delete Tenerife 2030- Fin emisiones

---

TELEVISION.md

La emision libre fue durante el confinamiento, Ahora ya es un canal cerrado, solo disponible a clientes de dicha operadorade cable

Delete Montilla tv

---

RADIO.md

Borrada Radio Joven Digital. Es un taller de Radio formativo juvenil y no emite en meses.

Add Alcira Radio & MUZ.FM ,Delete Radio Joven

---

RADIO.md

Motivo no tiene emision propia y: https://www.alhama.com/digital/medios/noticias-medios/13430-el-fraude-de-radio-alhama-se-convierte-en-estos-momentos-en-un-fraude-criminal

Delete SER Alhama

---

TELEVISION.md

El enlace livestream no es tv en vivo.

Update Enlace TV Costa Rica

---

TELEVISION.md

El canal lleva sin emitir desde el 4 de Noviembre (https://www.facebook.com/acsnetworktv/posts/3443102215771092)

Delete M3U8 of ACS Network

---

RADIO.md

Radio Feria FM, ahora es ONE FM. ▷ EN DIRECTO. LOS TEMAZOS DE ONE FM

Update Radio Feria, New name & Web

---

RADIO.md

En diciembre de 2020 el grupo Editorial Prensa Ibérica negoció con Radio María España la venta de la emisora, que ya estaba siendo desmantelada a causa de un ERE. Finalmente, el 26 de abril de 2021, sobre las 22:15 horas, la 97.7 Valencia cesó definitivamente sus emisiones, y su frecuencia fue sustituida por la de Radio María.

Delete 97.7 Radio Levante

---

RADIO.md

No emite desde hace meses ( sin asignación de frecuencia, solo online), y web y Facebook Muertos desde Diciembre

Delete Ciudad FM

---

TELEVISION.md

Ya esta muerto total. Ni dominio web, ni actividad en redes sociales

Delete Cachipum TV

---

RADIO.md

Después de la compra del Grupo 4 Baleares, no tienen ningún enlace valido, en redes sociales. Pongo los links oficiales de dichos logos en su web

Update Canal 4 Ràdio y  Radio Murta  Logos

---

RADIO.md

Ya vuelven a emitir desde la web principal por la que emitían antes.

Update Onda Fuenmayor

---

TELEVISION.md

Ya no emite en abierto y Geolocaliza sus emisiones.

Replace Fox News by FOX Live Now USA

---

RADIO.md

Ya NO emiten por la web ni en Fm, he llamado para preguntar y me han dicho que ya no funciona desde hace semanas por cierre de esta emisora.

Delete Los 40 Zafra-Río Bodión

---

RADIO.md

La antigua dirección web de Europa FM pertenecía a la antigua emisora de Atresmedia "Melodiafm Gandía" ya que esta ya NO existe y está cerrada, por lo que he tenigo que poner la nueva web.
Y respecto al nuevo stream, han creado un nuevo player en la web por lo que el antíguo directo ya no funciona. Lo pasé de mp3 a stream.

Update Europa FM Gandia

---

RADIO.md

La emisora ZFm Zaragoza después de varios años ha cerrado y en su frecuencia que era la 107.3 ahora en esa frecuencia emite Decisión Radio. Un saludo

Delete ZFM Zaragoza

---

TELEVISION.md

Fusión Guadalajara Media & Guada TV: Pasando a llamarse: Guada TV Media.Ya tienen la mosca y logo de la emisión nueva actualizado
https://www.youtube.com/watch?v=iztVTYQAcG

Fusión Guadalajara Media & Guada TV

---

RADIO.md

Radio 4G Iscar fin actividad en Valladolid. Emisora principal ( Valladolid) anuncio cierre: https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2FRadio4GVLL%2Fposts%2Fpfbid026DdCkgEyeLUzWgW1qSZanH443sHAJXrWFuRdTDHWy1oMnddnoKosBXEAzDbqYrRvl&show_text=true

Remove 4G Iscar

---

RADIO.md

Sin emisión propia, actividad nula en la web y en Facebook. La apk redirige sus emisiones a Motiva FM. ya en la lista

Delete Xtra Hits FM

---

RADIO.md

ACUP radio se ha apagado
La emisora universitaria palentina se transformará en la nueva comisión de ‘Twitch’ de la asociación Tras más de diez años n las ondas, la emisora universitaria palentina ACUP Radio cesa sus emisiones. La radio joven, creada por y para los jóvenes ha apagado definitivamente sus emisiones tras acercar durante más de una década la información …

Delete ACUP Radio ( Fin de emisión )

---

TELEVISION.md

La emisión internacional TV3CAT solo tiene un link, para las peticiones web fuera de España

Update TV3CAT streams and web link

---

TELEVISION.md

"Factoría de Carnaval  FDC y Radio Carnaval GC se han unido y poco a poco te vamos a ir desvelando muchas sorpresas"

Rename Carnaval TV to Factoría de Carnaval, update web & Logo

---

RADIO.md

Actualmente hay dos emisoras con este nombre en Madrid:
Radio inter 93.5 FM Madrid, actual director Carlos Hernando Gómez Peñaloza
Radio Intercontinental 95.4 FM Madrid, actual director Enrique Riobóo De la Vega
Radio Intercontinental vuelve a las ondas con gran respaldo del mundo político, periodístico y cultural de Madrid (20 de septiembre 2023, Intercontinental Madrid retomó anteayer sus emisiones de la mano de Canal 33 TV con un maratón de 12 horas de duración por el que pasaron para dar su apoyo representantes de la política y el municipalismo madrileño y también del mundo periodístico y de la cultura)

Add  Radio Intercontinental (Peticiones)

---

RADIO.md

Ambas llevan meses sin emisión, la primera típica radio municipal, sin mantenimiento, y actualmente sin redes sociales, la segunda se ha centrado en sus emisiones musicales vía tv.

Delete Ràdio Sol Albal & VIVA Radio

---

TELEVISION.md

Cambio el nombre porque creo que alguien nos metió un gol, esta emisión especial web es solamente utilizada ocasionalmente, para eventos especiales. No es solo para retrasmitir Toros

Rename  Canal Extremadura Toros to Canal Extremadura WEB

---

RADIO.md

Radio Camargo: La emisora municipal, lleva mas de 6 meses sin emitir,  sin actualizar web ni redes sociales.

Delete Radio Camargo, Add Cantabria FM

---

TELEVISION.md

Canal 33 fue un canal de televisión de El Salvador creado el 20 de enero de 1995 por la Universidad Tecnológica de El Salvador tras la clara respuesta a Telecorporación Salvadoreña de ser un rival televisivo de El Salvador. Debido a una crisis qué se enfrentaba a inicios de 2023, el canal cerró transmisiones el 1 de marzo.

Delete Canal 33 El Salvador, Replace by Canal 12 El Salvador

---

RADIO.md

El fallido proyecto de Onda Gran Canaria, cambia a 9 Radio.

Replace Onda Gran Canaria by 9 Radio

---

TELEVISION.md

Cambio de nombre de Erlo TV a GUKA TB

Replace Erlo to GUKA TB, new name,web & logo

---

TELEVISION.md

Antes de la temporada de 2024, el circuito fue comprado por Qatar Sports Investments (QSI) y absorbido por la Premier Padel, convirtiéndose en el sucesor como circuito profesional internacional de referencia.

Replace World Padel Tour by Premier Padel

---

RADIO.md

Cierre del grupo BOM Radio: http://www.lamoscamediatica.com/2024/10/squirrel-media-despide-todos-los.html Se mantiene la emisora independiente de  BOM Radio Benidorm, posible cambio de su marca en unos días.

Delete BOM Radio Zaragoza & BOM Radio (Cierre del grupo BOM Radio)

---

RADIO.md

Fin de emisiones
"Tras la despedida de emisiones en directo en la mañana de ayer, a partir de este sábado hasta el 15 de octubre, escucharemos durante 24 horas, solo, una ininterrumpida y variada selección musical, intercalando durante la jornada diurna nuestros compromisos comerciales. Escuchamos el indicativo informativo que emitimos."

Delete Radio 21

---

TELEVISION.md

Previsión del cambio, a la nueva emisión del reality en Enero 2025

Rename GH 24h to GH DÚO 24h

---

TELEVISION.md

Eliminado Canal  9 Soria (Ya no emite en internet desde hace 3 meses)
Actualizado Stream de Canal 54

Cambios en CYL

---

RADIO.md

Onda Ilicitana ya no existe como tal y ni web, ni emisión propia el enlace no https retrasmite, COPE Elche.

Delete Onda Ilicitana & add Spectra FM

---

RADIO.md

La emisión de Hit Radio Pirineos, tiene múltiples problemas técnicos con desconexiones frecuentes, Cambio a la emisión principal mas estable

Replace Hit Radio Pirineos by Hit Radio Zona Oriental

---

TELEVISION.md

Añadir los canales parlamentarios autonómicos que faltan:
- Cortes de Aragón. 
- Parlamento de Canarias. 
- Parlamento de Cantabria. 
- Asamblea de Extremadura. 
- Parlamento de Galicia. 
- Xunta de Galicia. 
- Gobierno de Castilla-La Mancha. 
- Parlament de les Illes Balears. 
- Junta General del Principado de Asturias. 
- Asamblea Regional de Murcia.

Canales parlamentarios autonómicos 

---

RADIO.md

Fin de emisiones y cierre anunciado en su Facebook: Radio Círculo se apaga. Siempre  es triste cuando una radio queda en silencio, y nos empobrece la  desaparición de un medio de comunicación. 25 años de ilusión,  trabajo y también muchas dificultades y pérdidas, en FM y en la posterior emisión  online. El domingo 20 de julio es el último día de emisión. Solo queda dar las gracias de corazón a todos los programas, a las personas colaboradoras que, con su trabajo, han dado vida a esta radio, y a las que habéis estado al otro lado, compartiendo pasión por la cultura. Mil gracias.

Delete Círculo de Bellas Artes Madrid
