LaQuay/TDTChannels

LICENSE
RADIO.md
TELEVISION.md
script/ambit.py
script/country.py
script/my_script.py
script/public/utils.py

Ahora los canales de TDT están divididos a nivel autonómico y locales.

Update TDT architecture

---

TELEVISION.md

Homogeneización a 320px de la resolución de los logos enlazados desde wikimedia.org

Homogeneización resolución logos wikimedia.org

---

TELEVISION.md

Añadidos nuevos EPG

---

RADIO.md

Hola,
Con esta pull arreglo Rock FM, Canal Fiesta Radio y Canal Flamenco.
Saludos y gracias por el proyecto!

Fix some radios

---

TELEVISION.md

Error en Canal Sur HD, es Canal Sur Andalucía. Se corrige nombre y EPG.

Correción de errores

---

TELEVISION.md

Errata en EPG

---

TELEVISION.md

Update canales Islas Baleares

---

TELEVISION.md

TV Murciana, eliminado EPG
Popular TV Murcia, eliminado EPG

Update canales Murcia

---

TELEVISION.md

Popular TV La Rioja, eliminado EPG

Update canales La Rioja

---

AUTHORS.md
TELEVISION.md

eitb deportes añadido a la lista de canales en sección deportes

eitb deportes añadido a la lista de canales en sección deportes

---

TELEVISION.md

fixing channels

---

TELEVISION.md

Se añade el Canal ocasional de Aragón deportes

aragon deportes

---

AUTHORS.md
script/channel.py
script/radio_script.py
script/tv_script.py
script/utils.py

Este es el listado que propongo para mejorar el json:
- La raíz era un array de objetos totalmente diferentes, mejor un diccionario para separarlos (`license`, `countries`, etc) y usar siempre un mismo objeto en un array
- Faltaba la url del epg para saber donde buscar el `epg_id`
- Añadido `updated` en la raiz para saber cuando fue actualizado el json
- Dentro de la información de un canal se ha añadido una key nueva (`type`) para indicar que tipo de stream es (`Video` o `Audio`)
- Dentro de el diccionario de la url del stream se ha añadido `extra_info`, donde se indica si ese stream es `GEO`, ya que no todos los streams del canal tiene que tener la misma información
- `extra_info` del canal ahora es un array para poder tener un listado de propiedades y no usar un string con todas las …

Nueva propuesta para el archivo json

---

TELEVISION.md

ETB Deportes
Canal Terres de l'Ebre

Añadidos 2 ID's de EPG

---

TELEVISION.md

Añadido enlace de Televisió d'Eivissa i Formentera

Añadido stream de TEF

---

TELEVISION.md

rai news 24

---

RADIO.md

Añadida CodeRadio en Internacionales.

Added CodeRadio station

---

RADIO.md
TELEVISION.md

Gracias al usuario del grupo "Wright 1973" por el aviso 👍🏼

Actualización de tres logos y un nombre de canal

---

TELEVISION.md

Coregido logo del Anterior pach

Añadir Caceres Teve logo corregido Facebook

---

README.md

- Androidsis 
- Tecnocincuentones

Añadidas 2 noticias

---

TELEVISION.md

Mejora del anterior link a 360p por link a 1080

Update Canal Sierra de Cádiz de 360p a 1080

---

TELEVISION.md

La emisión web esta Geo-localizada solo he podido conectarme utilizando VPN Alemana

Delete Deluxe Music Geolocalizado Solo Alemania

---

TELEVISION.md

TV Almansa solo W3U

---

TELEVISION.md

Correcion de 4 canales youtube para que carguen correctamente en Wiseplay

OT 24H, Malaga 24h, Huelva tv y etc sin &feature=youtu.be

---

TELEVISION.md

Suprimida las www, del inicio en la dirección de youtube que impedía cargar correctamente en w3u.Todos los dias Aprendiendo;-)

Update OT 24 Malaga 24h Huelva tv y Trebujena wiseplay

---

TELEVISION.md

Parece que a estos chicos no les gusta nuestros updates ;-) yo sigo

Update Malaga 24H Youtube w3u

---

RADIO.md

Añadida a petición de miembro del grupo

Add Inolvidable FM  Gran Canaria

---

RADIO.md

Se ha dejado link a pagina de programacion por si fuese util para el EPG

Añadido Vox UJI Radio

---

TELEVISION.md

Incluir Vinx Tv en Asturias PR @CarlosGN97

---

RADIO.md

Actualizadas varias radios Asturianas, suprimida radio fantasía es una radio hispana??? desconozco quien la puso aquí. Añadida Cope Oviedo .

Update Radios Asturianas

---

RADIO.md

Add  Play Radio Valencia y Gozadera FM PR@Hispared

---

RADIO.md

Perdona Marc no se donde salio ese 0 ??? Sorry

Update logo La Flamenca FM

---

RADIO.md

Corrijo enlace de Cope Deportes...con el .m3u los programas incluido TDT channels apk no lo reproducen

Update Cope Deportes; Add Sevilla y Betis m3u8

---

RADIO.md

Gestiona Radio cerro en el 2019: https://es.wikipedia.org/wiki/Gestiona_Radio

Update Radio Enlace , Delete Gestiona Radio

---

RADIO.md

Radio Sele Cerro emisión mucho hace tiempo y ya no tiene ni web

Delete Radio Sele ,Add APQ Radio y  Corredoria Suena

---

TELEVISION.md

Hola!
Descubrí este proyecto hace poco y me parece muy interesante.
Propongo añadir el canal ABC News Live (de EEUU) al listado de internacionales.
Muchas gracias.

Añadir ABC News Live (USA) a las TV internacionales

---

RADIO.md

Corrección  de alguna metedura de Pata en algún enlace y logo mal colocado

Update Radio corrección errores PR previos

---

RADIO.md

Delete : Sin emisiones ni web propia,Russkoe RadioRadio Mallorca

Update Illes Balears WICE Fixes

---

RADIO.md

Update País Vasco WICE Fixes

---

TELEVISION.md

Mi primer Pull request. Lo he hecho con algo que es pequeño para ir probando esto, y así en un futuro poder colaborar de una forma más efectiva.

Corregido nombre de "Radio U" a "RadioU TV"

---

TELEVISION.md

Borrados tambien gym y hits no estan en la web ya.

Update HQM Channels

---

TELEVISION.md

Parece que ya dejaron de jugar añadido el ultimo HQM Hits

Add HQM Hits

---

TELEVISION.md

Update HQM Logos and add HQM Gym

---

TELEVISION.md

Update HqM Classic logo

---

TELEVISION.md

Hola, aquí les dejo el NUEVO m3u8 de PopularTv Cantabria:
https://limited12.todostreaming.es/live/ptvcantabria-livestream.m3u8
Muchas gracias😊

NUEVO m3u8 PopularTv Cantabria

---

TELEVISION.md

http no funciona ya, cambio a https

Update UD Las Palmas TV

---

RADIO.md

Sin emisión en su web y webs de Terceros

Delete Onda Diamante y SER Maestrat

---

RADIO.md

Actualizado a su nueva emisión integrado en el Grupo Radio 4G

Update logo & name La Corredoira Suena

---

RADIO.md

Expand compatibility with other players

Update La Única FM, expand compatibility.

---

TELEVISION.md

Vuelve a emitir con canal live en Youtube

Add Axartel TV

---

TELEVISION.md

Actualizo al nuevo, en el antiguo enlace ponen el nuevo canal Madrileño TB Madrid

Update Guada TV

---

RADIO.md

FIX en algunos reproductores no funciona sin el ;

Update Radio La Guancha

---

TELEVISION.md

TB Madrid jugando al despiste:-)

Update TB Madrid

---

TELEVISION.md

ikono On Demand is a €4,99 monthly subscription-based program
that allows viewers access to exclusively curated playlists of the world’s most famous artworks,
filmed in our unique ikono style.

Delete Ikono TV

---

RADIO.md

Mismo motivo sin emision propia es un repe de Ser Granada

Delete Ser Loja

---

RADIO.md

Corrección link del stream Styl Manresa, duplicado erróneamente con Styl Classics Manresa

Update to correct wrong link:  Styl Manresa

---

TELEVISION.md

Add ETB Ocasional 1 y 2

---

RADIO.md

Delete Qué Radio & Radio Fuga

---

TELEVISION.md

Cese de actividad explicado en su Facebook: https://www.facebook.com/lacarolinadigital/?__cft__[0]=AZVjwU2-6g20Cyq0UpS1LB8R165lKj_TyQx-0lwNBxGYf62Gf7BzGusD1ArAFwuqQ98bDaCcz2g9bzpLDAnd5mDxfigc0VCYkX7ClZixBdb2VyiPcdszllfnyRw2kSFCrXR6A81FEqCJUDxUpgUqwvg-aPJ6SlkjEvSiv-qYfzUViA&__tn__=-UC%2CP-R .Ya no tienen ni web activa

Delete La Carolina Digital

---

RADIO.md

Se añade la emisora local Ràdio Voltregà (Osona)

Add Ràdio Voltregà

---

TELEVISION.md

Add TV L'Hospitalet

---

RADIO.md

Emisora de los universitarios palentinos perteneciente a la Asociación Cultural Universitaria Palentina (ACUP)

Add ACUP Radio Palencia

---

TELEVISION.md

Continuando con #1210. También añado al canal peruano Willax TV que está basado en Dailymotion.

Añadir Willax Perú

---

TELEVISION.md

Este pull request añade otro canal amazónico llamado Via Televisión (ViaTV), incluido sitio web.

Add Via Television

---

TELEVISION.md

Este pull request añade al canal peruano de música de cumbia La Karibeña.

Add La Karibena

---

TELEVISION.md

Este pull request añade el canal deportivo venezolano Meridiano.

Add Meridiano Venezuela

---

RADIO.md

- Radio Veritas
- Radio Arlanzón
- Radio Briviesca
- Miranda FM

Add Radios

---

TELEVISION.md

Este pull request añade el medio indio RepublicWorld en dos idiomas

Add RepublicWorld

---

TELEVISION.md

Este pull request añade dos canales infantiles, Paka Paka (Argentina) y 3ABN Kids (Estados Unidos).

Add Paka Paka Argentina

---

TELEVISION.md

Este pull request añade una emisora europa en idioma ruso que abarca en mayoría a temas de países como Ruisa y Crimea.

Add Current Time TV

---

TELEVISION.md

Este pull request añade al canal de noticias desde la India NDTV.

Add NDTV 24x7 India

---

RADIO.md

COPE Alcoy, COPE Onda Naranja, Radio 4G Onda Ilicitana, Radio 4G Benidorm, Onda Azul Torrevieja y Radio 4G Zaragoza

Add Radios Hoja de peticiones

---

TELEVISION.md

Update IB3 Global

---

TELEVISION.md

Update Zafra TV

---

TELEVISION.md

Este pull request añade el canal de Panamá transmitido a nivel nacional. [Más info](https://es.wikipedia.org/wiki/Nex) en Wikipedia.

Add Nex TV

---

RADIO.md

añadido emisora radio negreira

add radio negreira

---

TELEVISION.md

Ni emision, ni web, nianananana:-)

Delete Canal Cultura Gitana

---

TELEVISION.md

Este PR añade otro [canal principal](https://es.wikipedia.org/wiki/PAT_(canal_de_televisi%C3%B3n)) de Bolivia.

Add Red Pat

---

TELEVISION.md

Update Huelva TV

---

TELEVISION.md

el m3u8 solo funciona los findes cuando hay programa de 10 de la mañana a 14  h .

Update m3u8 Del 40 al 1

---

RADIO.md

A petición añado a  País Vasco , solo estaba en Nacionales

Add Euskadi Irratia

---

RADIO.md

ADD Radio Gorbea y Radio Donosti

---

TELEVISION.md

Update La Tele Tuya Venezuela

---

TELEVISION.md

Update RTVE Web links

---

RADIO.md

Se borra sin actividad, web suspendida, y sin publicaciones en las redes sociales

Delete  Más FM Begastri & Add Wifon FM

---

TELEVISION.md

Especial para pieles sensibles.

Move Xaloa Telebista to C. Foral de Navarra :-)

---

RADIO.md

Cambio formato del stream para corregir problema con ciertos reproductores

Update FIX Cadena Mix

---

TELEVISION.md

Delete Huesca TV

---

RADIO.md

Sin emisiones, ni actividad en redes sociales desde principios de año.

Delete Radio Dance

---

RADIO.md

Cambio de Nombre y web de la emisora

Replace Radio YA by Decision Radio

---

RADIO.md

Delete RNA Andorra, Add Enisoras d Andorra sin token:-)

---

RADIO.md

Tras la compra de mi flamante teclado Gamer Retroiluminado, Decisión Radio se escuchara a la perfección.
Disculpar las molestias ocasionadas

Update Decisión Radio después de cómprame, teclado con acentos

---

RADIO.md

Añadido el tag WICE para Wiseplay y derivados

Europa FM Huelva WICE fix

---

RADIO.md

Servidor y web siempre caidas. No merece la pena que este en lista

Delete Radio La Guancha

---

RADIO.md

Cambio a la emisora principal de Jazz Radio

Update Jazz Radio Francia

---

RADIO.md

Delete MUZ.FM & Última Hora Mallorca

---

TELEVISION.md

Delete Secret Story 24h

---

info_television.md

Delete Secret Story 24h Info_tv

---

RADIO.md

Sin emisiones, long time ago :-)

Delete Metro FM & EcoRadio

---

TELEVISION.md

TV Extremeña fix

---

TELEVISION.md

Update EITB Basque, ETB Eventos 1 y 2

---

TELEVISION.md

Funciona los Sábados desde las 08:50 h en la web de Cadena100: https://www.cadena100.es/programacion.

ADD De Sábado con Christian Gálvez (CADENA 100)

---

TELEVISION.md

Delete emisión 2 TV Canaria

---

TELEVISION.md

No es una emisión ya, simplemente VOD.

Delete UHD Spain

---

RADIO.md

Corregido el enlace, apuntaba a la emision principal de Madrid, no a LOS40 Almería

Update LOS40 Almería

---

RADIO.md

También actualizo webs de Radio Murta y Canal 4 Ràdio

Update Canal 4 Radio & Titoieta Ràdio & Formentera Radio & Radio Murta

---

TELEVISION.md

Mediaset apreto el boton de la Risa.

Update mtmad 24h

---

TELEVISION.md

Delete Harley Davidson TV Channels

---

RADIO.md

Cambio de Nombre a Onda Langreo y nuevo enlace web. Se actualiza también el stream, por que el antiguo en breve dejara de funcionar

Update La Cuenca Radio to Onda Langreo

---

RADIO.md

Pongo el logo oficial, al no aparecer logo especifico

Update Radio 4G Iscar Logo

---

TELEVISION.md

Borro Nos tv. Solo trasmite en la televisión por cable R Galicia.

Update Hermes TV. Delete Nos TV

---

RADIO.md

Borro por cierre: https://redactoresespecializados.es/radio-inter-918-onda-media-cierra/

Delete Radio Inter

---

RADIO.md

No emite, pasa a ser una playlist en Spootify

Delete Happy FM

---

TELEVISION.md

La operadora de cable Mapeka ya no emite en abierto, solo clientes

Delete TeleArchena Add Canal 1 Mar Menor

---

RADIO.md

Borro Standfy por anuncio fin de actividad.

Delete Standfy FM, Add  VIVA Radio

---

TELEVISION.md

Delete Medial TV

---

RADIO.md

Update: New name  Onda Langreo now Medea FM

---

TELEVISION.md

Pàsa a PPV, y peticion de borrado de links por parte de la productora

Delete UD Las Palmas TV

---

RADIO.md

Falta de actividad, emision web y redes sociales

Delete Radio Las Águilas y TodoExitosRadio

---

RADIO.md

Actualizados todos los links territoriales de radio a la nueva web de RTVE

Update RNE Territoriales Web links

---

RADIO.md

Cambio de Nombre: https://redactoresespecializados.es/radio-4g-cambia-de-nombre/

Update Radio 4G to BOM Radio

---

RADIO.md

La emisora pasa al grupo Radio Intereconomía , ya no esta en R4G

Update Onda Ilicitana name & Logo

---

RADIO.md

Añadidos canales tematicos de Standfy, y enlace web nuevo al reproductor

Update Standfy FM

---

RADIO.md

La antigua dirección web, ya tiene un redireccionamiento a la nueva

Update CMM Radio stream & web Link

---

TELEVISION.md

Aparte de no emitir, cierre de web y redes sociales

Delete Televisión de Alicante

---

TELEVISION.md

Se adapta al nombre real del canal, adaptado al lenguaje de signos

Rename Canal Sur 2 Andalucía to Canal Sur 2 Accesible

---

RADIO.md

Fix para reproductores basados en Exoplayer, No reproducen el m3u8.

Fix CMM Radio

---

RADIO.md

Lleva meses inactiva, y con la web en supuesta renovación

Delete Radio 7 Valencia

---

RADIO.md

Ya han añadido por fin un enlace STREAM para que se pueda escuchar en la app y fuera de la web de Vive! Radio ;)

ADD Stream Vive! Radio

---

RADIO.md

All fin la nueva emisión de Radio ya carga en reproductores Exoplayer

Update CMM Radio

---

TELEVISION.md

La nova televisió de Vila-real

Add Veteve

---

RADIO.md

"Factoría de Carnaval  FDC y Radio Carnaval GC se han unido y poco a poco te vamos a ir desvelando muchas sorpresas".

Update Radio Carnaval web & Logo

---

TELEVISION.md

Update Best Cable Sports Perú

---

RADIO.md

Game over
https://www.gacetadeprensa.com/noticia/12679/medios/multas-millonarias-o-cambio-de-nombre:-el-misterio-detras-del-cierre-de-decision-radio.html

Delete Decisión Radio &  Decisión Radio Galicia

---

info_television.md

Delete 8 TV Info_tv

---

RADIO.md

Se suprime SER Arnedo, ya no forma parte de la cadena SER

Update La Rioja & Melilla SER web links

---

RADIO.md

La coloco al lado de La Mas FM, por emitir ambas en Almuñécar

Add Noventa Radio (peticiones)

---

RADIO.md

fin de actividad, web y redes sociales

Delete Via Radio

---

TELEVISION.md

Delete Operación Triunfo

---

RADIO.md

Delete ON Radio

---

TELEVISION.md

Delete GH DUO 24h

---

TELEVISION.md

Se suprime emisión 1 por no funcionar

Update TVE Int. Europa

---

TELEVISION.md

https://revistaecclesia.es/la-diocesis-de-san-sebastian-anuncia-el-cierre-de-betania-tv/

Delete  Betania TV

---

RADIO.md

Cambio en la marca de la emisora

Rename Libertad FM to Radio Libertad

---

RADIO.md

Delete Radio Tropical

---

TELEVISION.md

Update TeleAmazonas Ecuador

---

RADIO.md

Sin actividad ni en web, ni en redes sociales desde hace años

Delete Canora Radio

---

RADIO.md

Llevan dos semanas caídas. Menos es mas, no solo es ponerlas, también es verificar que funcionen, y descartar emisiones ocasionales que funcionan una vez o 2 al año. Eso no aporta al proyecto solo resta y da trabajo innecesario.

Delete ONE Replay, Hot & Dance

---

RADIO.md

Fin de actividad:
https://www.instagram.com/p/C9X9O-zuDjQ/?utm_source=ig_web_copy_link

Delete La Rumbera

---

TELEVISION.md

Delete Spektra TV España

---

TELEVISION.md

Delete Canal 12 El Salvador

---

TELEVISION.md

Add Televen TV Venezuela

---

TELEVISION.md

Delete 101TV Costa del Sol

---

RADIO.md

Desaparecen de la parrilla de Cadena Dial

Delete DIAL MINI & DIAL Esencial

---

RADIO.md

Delete La Voz de la Axarquía

---

TELEVISION.md

Delete Otto FM Italia

---

info_television.md

Información sobre W3U eliminada, así como alguna errata de formato corregida

Información sobre W3U eliminada

---

TELEVISION.md

Cambio de contenido de STZ Telebista, ya no es una cadena musical

Move fron Musicales to P. Vasco STZ Telebista

---

RADIO.md

El logo de Facebook no rula:-)

Update Spektra FM Logo

---

TELEVISION.md

Delete GH DÚO 24h

---

RADIO.md

Update Wifon FM

---

TELEVISION.md

Delete Vivamóvil TV

---

RADIO.md

El stream de Inter Radio Murcia estaba cambiado por uno de La Jungla

Update Inter Radio wrong stream

---

TELEVISION.md

Delete RTVE Dia de la Tierra & dia del Libro add RTVE Eurovisión

---

RADIO.md

Delete Radio San Martín & Radio Bronka

---

RADIO.md

Logo de Facebook, no se ve en la apk, se sustituye por su logo web, de mejores dimensiones

Update Radio Calasparra Logo

---

RADIO.md

Fin de actividad de Radio Teide

Replace Radio Teide by Radio 6 Tenerife

---

RADIO.md

Update Mortal FM (corregido)

---

TELEVISION.md

- Añadir Saja Nansa TV (Cantabria).
- Añadir los Gobiernos autonómicos. 
- Corregir el stream de TV Carmona. 
- Añadir los canales religiosos "Cristiana TV" España" y "ÉL TV España". 
- Añadir el canal Internacional "WIPR Puerto Rico".

Añadir varios canales
